In [15]:
import pandas as pd

In [16]:
# import data, using the dataset I used for age
df = pd.read_csv('/Users/agneslu/Desktop/neighborhood-data/analysis/age/ACSDP5Y2023.DP05-Data.csv')

In [17]:
df.head(3)

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0090PM,DP05_0091PE,DP05_0091PM,DP05_0092PE,DP05_0092PM,DP05_0093PE,DP05_0093PM,DP05_0094PE,DP05_0094PM,Unnamed: 378
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,1400000US06075010101,Census Tract 101.01; San Francisco County; Cal...,2004,297,1077,173,927,187,116.2,23.6,...,2.9,(X),(X),1468,(X),58.4,6.3,41.6,6.3,NaN
2,1400000US06075010102,Census Tract 101.02; San Francisco County; Cal...,1795,345,786,172,1009,285,77.9,27.4,...,1.9,(X),(X),1425,(X),43.1,7.6,56.9,7.6,NaN

In [18]:
# drop the first column
df = df.drop(df.columns[0], axis=1)
df.head(3)

,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,DP05_0005E,...,DP05_0090PM,DP05_0091PE,DP05_0091PM,DP05_0092PE,DP05_0092PM,DP05_0093PE,DP05_0093PM,DP05_0094PE,DP05_0094PM,Unnamed: 378
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Under...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,2004,297,1077,173,927,187,116.2,23.6,62,...,2.9,(X),(X),1468,(X),58.4,6.3,41.6,6.3,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1795,345,786,172,1009,285,77.9,27.4,45,...,1.9,(X),(X),1425,(X),43.1,7.6,56.9,7.6,NaN

In [19]:
# change NAME to Area
df = df.rename(columns={'NAME': 'Area'})
df.head(3)

,Area,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,DP05_0005E,...,DP05_0090PM,DP05_0091PE,DP05_0091PM,DP05_0092PE,DP05_0092PM,DP05_0093PE,DP05_0093PM,DP05_0094PE,DP05_0094PM,Unnamed: 378
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Under...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,2004,297,1077,173,927,187,116.2,23.6,62,...,2.9,(X),(X),1468,(X),58.4,6.3,41.6,6.3,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1795,345,786,172,1009,285,77.9,27.4,45,...,1.9,(X),(X),1425,(X),43.1,7.6,56.9,7.6,NaN

In [20]:
# drop the margin columns
df = df[df.columns.drop(list(df.filter(regex='M')))]
df.head(3)

,Area,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0004E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,DP05_0009E,...,DP05_0086PE,DP05_0087PE,DP05_0088PE,DP05_0089PE,DP05_0090PE,DP05_0091PE,DP05_0092PE,DP05_0093PE,DP05_0094PE,Unnamed: 378
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex r...,Estimate!!SEX AND AGE!!Total population!!Under...,Estimate!!SEX AND AGE!!Total population!!5 to ...,Estimate!!SEX AND AGE!!Total population!!10 to...,Estimate!!SEX AND AGE!!Total population!!15 to...,Estimate!!SEX AND AGE!!Total population!!20 to...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,2004,1077,927,116.2,62,21,0,133,46,...,0.0,2.3,2.9,0.0,2.9,(X),1468,58.4,41.6,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1795,786,1009,77.9,45,46,79,97,109,...,0.9,0.0,2.5,0.0,2.5,(X),1425,43.1,56.9,NaN

In [21]:
# rename columns
column_mapping = {}
for i, col in enumerate(df.columns):
    if i < len(df.iloc[0]):  # Make sure we don't go out of bounds
        column_mapping[col] = df.iloc[0, i]

df = df.rename(columns=column_mapping)
df.head(3)

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,...,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some Other Race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races including Some Other Race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",NaN
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex r...,Estimate!!SEX AND AGE!!Total population!!Under...,Estimate!!SEX AND AGE!!Total population!!5 to ...,Estimate!!SEX AND AGE!!Total population!!10 to...,Estimate!!SEX AND AGE!!Total population!!15 to...,Estimate!!SEX AND AGE!!Total population!!20 to...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,2004,1077,927,116.2,62,21,0,133,46,...,0.0,2.3,2.9,0.0,2.9,(X),1468,58.4,41.6,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1795,786,1009,77.9,45,46,79,97,109,...,0.9,0.0,2.5,0.0,2.5,(X),1425,43.1,56.9,NaN

In [22]:
# remove the first row
df = df.drop(df.index[0])  
df = df.reset_index(drop=True)
df.head(3)

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,...,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some Other Race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races including Some Other Race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",NaN
0,Census Tract 101.01; San Francisco County; Cal...,2004,1077,927,116.2,62,21,0,133,46,...,0.0,2.3,2.9,0.0,2.9,(X),1468,58.4,41.6,NaN
1,Census Tract 101.02; San Francisco County; Cal...,1795,786,1009,77.9,45,46,79,97,109,...,0.9,0.0,2.5,0.0,2.5,(X),1425,43.1,56.9,NaN
2,Census Tract 102.01; San Francisco County; Cal...,2608,1325,1283,103.3,56,48,57,68,149,...,0.0,0.0,7.5,0.3,7.1,(X),2126,50.1,49.9,NaN

In [23]:
# change Geographic Area Name to Area
df = df.rename(columns={'Geographic Area Name': 'Area'})

In [24]:
# keep area and total population columns
df = df[['Area', 'Estimate!!SEX AND AGE!!Total population']]
df.head(3)

,Area,Estimate!!SEX AND AGE!!Total population
0,Census Tract 101.01; San Francisco County; Cal...,2004
1,Census Tract 101.02; San Francisco County; Cal...,1795
2,Census Tract 102.01; San Francisco County; Cal...,2608

In [25]:
# only keep numbers for the area column
df['Area'] = df['Area'].str.replace(r'.*Census Tract\s+', '', regex=True)  # remove everything before tract number
df['Area'] = df['Area'].str.replace(r';.*', '', regex=True)  # remove everything after semicolon
df['Area'] = df['Area'].str.strip()  # remove any extra whitespace
df

        Area Estimate!!SEX AND AGE!!Total population
0     101.01                                    2004
1     101.02                                    1795
2     102.01                                    2608
3     102.02                                    1761
4        103                                    3791
..       ...                                     ...
239  9805.01                                     155
240     9806                                    1290
241     9809                                     322
242     9901                                       0
243     9902                                       0

[244 rows x 2 columns]

In [26]:
# change the total population column name
df = df.rename(columns={'Estimate!!SEX AND AGE!!Total population': 'Total Population'})
df.head(3)

     Area Total Population
0  101.01             2004
1  101.02             1795
2  102.01             2608

In [27]:
# convert numeric columns to proper data types
numeric_columns = ['Total Population']
df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'value': df.set_index('Area')['Total Population'].to_dict(),
}

# convert to JSON and save to file
import json

with open('/Users/agneslu/Desktop/neighborhood-data/data/population.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'population.json'")

JSON file saved as 'population.json'

In [28]:
# export the final dataframe to CSV
df.to_csv('/Users/agneslu/Desktop/neighborhood-data/analysis/crime/population.csv', index=False)